2024-03-09T16:20:20 {"cpu": 0.30224609375, "cpu_total": 8, "cpu_usage": 0.03778076171875, "memory": 2263.0, "memory_total": 4950.0, "memory_usage": 0.4571717171717172, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Pipeline mental_health_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1710001220.806105, "uuid": "cf9f7da9a11b4eec98cd272716f7b7dc"}
2024-03-09T16:20:20 {"cpu": 0.30224609375, "cpu_total": 8, "cpu_usage": 0.03778076171875, "memory": 2302.0, "memory_total": 4950.0, "memory_usage": 0.46505050505050505, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Pipeline mental_health_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1710001220.921965, "uuid": "68c7cbcfc59e4ebabb3b437d99ff30ec"}
2024-03-09T16:20:20 {"block_run_id": 1, "block_uuid": "load_mental_health", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline mental_health_pipeline block load_mental_health", "timestamp": 1710001220.951845, "uuid": "4b1c2df6f702409798a96b9af8d75d75"}
2024-03-09T16:20:23 {"block_run_id": 1, "block_uuid": "load_mental_health", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "BlockRun 1 (block_uuid: load_mental_health) completes.", "timestamp": 1710001223.84805, "uuid": "d034fe2040a04f6fb90a798c7ed2339e"}
2024-03-09T16:20:31 {"cpu": 0.29833984375, "cpu_total": 8, "cpu_usage": 0.03729248046875, "memory": 2274.0, "memory_total": 4950.0, "memory_usage": 0.4593939393939394, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Pipeline mental_health_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1710001231.120536, "uuid": "88f475baa9b8435388d73ad000454dac"}
2024-03-09T16:20:31 {"block_run_id": 2, "block_uuid": "transform_mental_health", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline mental_health_pipeline block transform_mental_health", "timestamp": 1710001231.26311, "uuid": "75b6bb51932c464a9d5be998fb495195"}
2024-03-09T16:20:33 {"block_run_id": 2, "block_uuid": "transform_mental_health", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "BlockRun 2 (block_uuid: transform_mental_health) completes.", "timestamp": 1710001233.889264, "uuid": "4c13b78d135140fc933279db01c14672"}
2024-03-09T16:20:40 {"cpu": 0.30029296875, "cpu_total": 8, "cpu_usage": 0.03753662109375, "memory": 2268.0, "memory_total": 4950.0, "memory_usage": 0.4581818181818182, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Pipeline mental_health_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1710001240.356918, "uuid": "979913bac7aa477786f896b3693c59b9"}
2024-03-09T16:20:40 {"block_run_id": 3, "block_uuid": "save_mental_health_gcs", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline mental_health_pipeline block save_mental_health_gcs", "timestamp": 1710001240.511184, "uuid": "7a60629fc81945e890411b49d4d89a7d"}
2024-03-09T16:20:41 {"block_run_id": 3, "block_uuid": "save_mental_health_gcs", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "EXCEPTION", "message": "BlockRun 3 (block_uuid: save_mental_health_gcs) failed.", "timestamp": 1710001241.568704, "uuid": "48f3a340ba184500a0541cf589dcc6a5", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1312, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1221, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1527, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1683, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1722, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_google_cloud_storage\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/google_cloud_storage.py\", line 126, in export\n    bucket = self.client.get_bucket(bucket_name)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/storage/client.py\", line 782, in get_bucket\n    bucket = self._bucket_arg_to_bucket(bucket_or_name)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/storage/client.py\", line 702, in _bucket_arg_to_bucket\n    bucket = Bucket(self, name=bucket_or_name)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/storage/bucket.py\", line 667, in __init__\n    name = _validate_name(name)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/storage/_helpers.py\", line 92, in _validate_name\n    raise ValueError(\"Bucket names must start and end with a number or letter.\")\nValueError: Bucket names must start and end with a number or letter.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1603, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 584, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1128, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["Bucket names must start and end with a number or letter."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1312, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1221, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1527, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1683, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1722, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_google_cloud_storage
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/google_cloud_storage.py", line 126, in export
    bucket = self.client.get_bucket(bucket_name)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/client.py", line 782, in get_bucket
    bucket = self._bucket_arg_to_bucket(bucket_or_name)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/client.py", line 702, in _bucket_arg_to_bucket
    bucket = Bucket(self, name=bucket_or_name)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/bucket.py", line 667, in __init__
    name = _validate_name(name)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/_helpers.py", line 92, in _validate_name
    raise ValueError("Bucket names must start and end with a number or letter.")
ValueError: Bucket names must start and end with a number or letter.
2024-03-09T16:20:50 {"cpu": 0.29638671875, "cpu_total": 8, "cpu_usage": 0.03704833984375, "memory": 2273.0, "memory_total": 4950.0, "memory_usage": 0.4591919191919192, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "mental_health_pipeline", "hostname": "f53698cf4b48", "level": "INFO", "message": "Pipeline mental_health_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1710001250.543087, "uuid": "efc8daa814f9408a8005c21ae9db8374"}
